name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Cache gradlew
      uses: actions/cache@v3
      with:
        path: .gradle
        key: ${{ runner.os }}-gradlew-${{ hashFiles('gradle/wrapper/**') }}
        restore-keys: |
          ${{ runner.os }}-gradlew-
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
        cache: gradle
    - name: Build and Test
      run: ./gradlew -Pkotest.proptest.default.iteration.count=1000 test
