name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Test:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache gradlew
      uses: actions/cache@v3
      with:
        path: .gradle
        key: gradlew-${{ hashFiles('gradle/wrapper/**') }}
        restore-keys: |
          gradlew-

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
        cache: gradle

    - name: Build and Test
      run: ./gradlew -P"kotest.proptest.default.iteration.count"=2000 test
