name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11

    - name: Build and Test
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: test
        gradle-version: wrapper
        properties: |
          kotest.proptest.default.iteration.count=1000      
